name: CI Pipeline

on:
  pull_request:
    branches:
      - test # 只有當有 PR 到 test 分支時觸發

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x' # 使用 Node.js 18 的最新次版本
          cache: 'pnpm' # 啟用 pnpm 的緩存

      - name: Install pnpm
        run: |
          echo "====== Installing pnpm ======"
          npm install -g pnpm

      - name: Install dependencies
        run: |
          echo "====== Installing dependencies ======"
          pnpm install

      - name: Run ESLint
        run: |
          echo "====== Run ESLint ======"
          pnpm run lint

      - name: Run Unit Test
        run: |
          echo "====== Run Unit Test ======"
          pnpm run test
