name: PetZone CICD

on:
  push:
    branches: ["test"]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2  # Optional: specify a pnpm version

  build:
    name: build
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo Directory
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'
          cache: 'pnpm'

  unittest:
    name: Run UnitTest
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo Directory
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'
          cache: 'pnpm'

      - name: Install Dependencies with pnpm
        run: pnpm install

      - name: Run Unit Test with pnpm
        run: pnpm run lint
